# Generated by Django 4.0.4 on 2022-04-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_fullname_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
