# Generated by Django 4.0.4 on 2022-04-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='title',
            field=models.CharField(default='Аниме Тян', max_length=128, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
