# Generated by Django 4.0.4 on 2022-04-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_mediacontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='media_type',
            field=models.CharField(choices=[('1', 'Изображение'), ('2', 'Видео'), ('3', 'Аудио')], default='1', max_length=20),
        ),
    ]
