# Generated by Django 4.0.4 on 2022-04-28 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_mediacontent_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='media_type',
            field=models.CharField(choices=[('1', 'Изображение'), ('2', 'Видео'), ('3', 'Аудио')], default='1', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='tags',
            field=models.ManyToManyField(to='content.tag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='ChosenMediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.mediacontent', verbose_name='Выбранный медиа-контент')),
                ('tags', models.ManyToManyField(to='content.tag', verbose_name='Выбранные теги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
